var keyList = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    "a",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m"
];

// "!": document.getElementById('key-1'),
// "@": document.getElementById('key-2'),
// "#": document.getElementById('key-3'),
// "$": document.getElementById('key-4'),
// "%": document.getElementById('key-5'),
// "^": document.getElementById('key-6'),
// "&": document.getElementById('key-7'),
// "*": document.getElementById('key-8'),
// "(": document.getElementById('key-9'),
// ")": document.getElementById('key-0'),
// "Q": document.getElementById('key-q'),
// "W": document.getElementById('key-w'),
// "E": document.getElementById('key-e'),
// "R": document.getElementById('key-r'),
// "T": document.getElementById('key-t'),
// "Y": document.getElementById('key-y'),
// "U": document.getElementById('key-u'),
// "I": document.getElementById('key-i'),
// "O": document.getElementById('key-o'),
// "P": document.getElementById('key-p'),
// "A": document.getElementById('key-a'),
// "S": document.getElementById('key-s'),
// "D": document.getElementById('key-d'),
// "F": document.getElementById('key-f'),
// "G": document.getElementById('key-g'),
// "H": document.getElementById('key-h'),
// "J": document.getElementById('key-j'),
// "K": document.getElementById('key-k'),
// "L": document.getElementById('key-l'),
// "Z": document.getElementById('key-z'),
// "X": document.getElementById('key-x'),
// "C": document.getElementById('key-c'),
// "V": document.getElementById('key-v'),
// "B": document.getElementById('key-b'),
// "N": document.getElementById('key-n'),
// "M": document.getElementById('key-m'),