var keyMap = {
    "1": document.getElementById('key-1'),
    "2": document.getElementById('key-2'),
    "3": document.getElementById('key-3'),
    "4": document.getElementById('key-4'),
    "5": document.getElementById('key-5'),
    "6": document.getElementById('key-6'),
    "7": document.getElementById('key-7'),
    "8": document.getElementById('key-8'),
    "9": document.getElementById('key-9'),
    "0": document.getElementById('key-0'),
    "q": document.getElementById('key-q'),
    "w": document.getElementById('key-w'),
    "e": document.getElementById('key-e'),
    "r": document.getElementById('key-r'),
    "t": document.getElementById('key-t'),
    "y": document.getElementById('key-y'),
    "u": document.getElementById('key-u'),
    "i": document.getElementById('key-i'),
    "o": document.getElementById('key-o'),
    "p": document.getElementById('key-p'),
    "a": document.getElementById('key-a'),
    "s": document.getElementById('key-s'),
    "d": document.getElementById('key-d'),
    "f": document.getElementById('key-f'),
    "g": document.getElementById('key-g'),
    "h": document.getElementById('key-h'),
    "j": document.getElementById('key-j'),
    "k": document.getElementById('key-k'),
    "l": document.getElementById('key-l'),
    "z": document.getElementById('key-z'),
    "x": document.getElementById('key-x'),
    "c": document.getElementById('key-c'),
    "v": document.getElementById('key-v'),
    "b": document.getElementById('key-b'),
    "n": document.getElementById('key-n'),
    "m": document.getElementById('key-m'),

    // "!": document.getElementById('key-1'),
    // "@": document.getElementById('key-2'),
    // "#": document.getElementById('key-3'),
    // "$": document.getElementById('key-4'),
    // "%": document.getElementById('key-5'),
    // "^": document.getElementById('key-6'),
    // "&": document.getElementById('key-7'),
    // "*": document.getElementById('key-8'),
    // "(": document.getElementById('key-9'),
    // ")": document.getElementById('key-0'),
    // "Q": document.getElementById('key-q'),
    // "W": document.getElementById('key-w'),
    // "E": document.getElementById('key-e'),
    // "R": document.getElementById('key-r'),
    // "T": document.getElementById('key-t'),
    // "Y": document.getElementById('key-y'),
    // "U": document.getElementById('key-u'),
    // "I": document.getElementById('key-i'),
    // "O": document.getElementById('key-o'),
    // "P": document.getElementById('key-p'),
    // "A": document.getElementById('key-a'),
    // "S": document.getElementById('key-s'),
    // "D": document.getElementById('key-d'),
    // "F": document.getElementById('key-f'),
    // "G": document.getElementById('key-g'),
    // "H": document.getElementById('key-h'),
    // "J": document.getElementById('key-j'),
    // "K": document.getElementById('key-k'),
    // "L": document.getElementById('key-l'),
    // "Z": document.getElementById('key-z'),
    // "X": document.getElementById('key-x'),
    // "C": document.getElementById('key-c'),
    // "V": document.getElementById('key-v'),
    // "B": document.getElementById('key-b'),
    // "N": document.getElementById('key-n'),
    // "M": document.getElementById('key-m'),
}